# Generated by Django 4.1.1 on 2024-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='movies', to='viewer.country'),
        ),
    ]
