# Generated by Django 4.1.1 on 2024-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_rename_actor_creator_rename_actors_movie_creators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='creators',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movie', to='viewer.creator'),
        ),
    ]
